### ISSUE TITLE
Please create a dedicated SVG logo for this workbench to be displayed in the Add-on Manager menu

### ISSUE THREAD

**Issue by luzpaz** [eddyverl/FreeCAD-Pyramids-and-Polyhedrons#1]
Please create an SVG for this workbench. We recommend following the FreeCAD [artwork guidelines](https://www.freecadweb.org/wiki/Artwork_Guidelines)

**Comment by eddyverl** [comment]
The name is Pyramids-and-Polyhedrons_workbench_icon.svg

you'll find it now on github in 
/icons
/Mod/Pytramids-and-Polyhedrons/resources/icons
and in the FreeCAD wiki
