### ISSUE TITLE
Not showing in Addon manager

### ISSUE THREAD

**Issue by macdroid53** [eddyverl/FreeCAD-Pyramids-and-Polyhedrons#3]
- this doesn't show up in the available workbenches in addon manager (0.19 daily build, linux)

**Comment by FreddieChopin** [comment]
Same here, also 0.19 and also Linux.

**Comment by Build-0-Matic** [comment]
The problem seems widespread across all platforms (0.19 Windows 64 bit).
Thankfully the manual install still works.

**Comment by eddyverl** [comment]
Thanks for the comments
I've not been active on FreeCad for a while.
I've tried in the past to add the polyhydrons workbench  to the addon manager but for some reason that didn't succeed.

I am now making another attempt. Hopefully with more success.

**Comment by eddyverl** [comment]
Done!  As of now the workbench is available in the FreeCAD addon-manager.
