### ISSUE TITLE
Pyramid can't be rotated in multiple axes at once.

### ISSUE THREAD

**Issue by Build-0-Matic** [eddyverl/FreeCAD-Pyramids-and-Polyhedrons#5]
This is maybe a bit of a FreeCAD quirk or a plugin Quirk.
Could it be possible to create the pyramid with the base on a different orientation than the default?
The fact that a 4 sided pyramid gets created with a 45° rotation angle forces the user to do multiple rotations of the model he's working on in order to accommodate the pyramid position and not the opposite like would be expected.
Not really a bug but a small flaw.

It's really cumbersome when you're building a viewfinder and need the pyramid to be sideways.

**Comment by eddyverl** [comment]
Thanks for the comment.
Indeed, tilting a shape to a specific angle is not easy.
I'm going to try to integrate a user-friendly method.

**Comment by eddyverl** [comment]
File polyhedrons.py has been modified so
   - all pyramids have a side parallel to the x axis by default
   - the z-angle is adjustable
Hope this helps.

**Comment by Build-0-Matic** [comment]
It sure will!
Thank you and Seasons Greetings to you and your family.
