### ISSUE TITLE
Resssources should be taken from intallation folder

### ISSUE THREAD

**Issue by plgarcia** [eddyverl/FreeCAD-Pyramids-and-Polyhedrons#6]
On windows MMods may be installed in %appdata%\FreeCAD\Mod or in folder defined in configuration. <Preferences>/<General>/<Macro>/<Macro Path>

In the second case, the module does not find the images. The module works with default Icons.

Log: Cannot open file 'D:/Profiles/pasgarci/AppData/Roaming/FreeCAD/Mod/Pyramids-and-Polyhedrons/Resources/Icons/pyramid.svg', because: Le chemin d�acc�s sp�cifi� est introuvable.
Log: Cannot open file 'D:/Profiles/pasgarci/AppData/Roaming/FreeCAD/Mod/Pyramids-and-Polyhedrons/Resources/Icons/pyramid.svg', because: Le chemin d�acc�s sp�cifi� est introuvable.

**Comment by eddyverl** [comment]
Check this please:
Have a look in your folder D:/Profiles/pasgarci/AppData/Roaming/FreeCAD/Mod/
The folder of the workbench has to be "Pyramids-and-Polyhedrons" and not "FreeCAD-Pyramids-and-Polyhedrons"

**Comment by plgarcia** [comment]
Dear Eddy,

You did not understand my pupose.

Any module can be installed in %AppData%/FreeCAD/Mod/  in my case 
D:/Profiles/pasgarci/AppData/Roaming/FreeCAD/Mod/

or in the folder defined in the conf in my case 
d:\profiles\pasgarci\google drive\EnCours\FreeCad\Macros\Mod

When it is installed in %ApData%/FreeCAD/Mod/ (%appdata%) what is the 
default, everything is working fine.

But when it is installed in the folder defined in configuration, the 
module is loaded and works but it does not find the resoources as shown 
in the logs. So all icons are a cros.


Regards
Pascal Garcia

Le 20/12/2020 à 18:06, Eddy Verlinden a écrit :

**Comment by eddyverl** [comment]
Possibly it has to do with the FreeCAD-python function    getUserAppDataDir () 

Try this out in the python console.
Print (str (FreeCAD.getUserAppDataDir ()))

I myself cannot help you.

Maybe the following link provides some inspiration.

https://forum.freecadweb.org/viewtopic.php?f=3&t=38194&p=323847&hilit=usb#p326112

Success with it.

**Comment by plgarcia** [comment]
Other modules work like this.

getUserAppDataDir returns the userdir not the installation dir of the 
module if installed somwhere else.

There must be another function to ientify the istalation folder of the 
module, or may be a relative path works!

When I have some-time I have a loo to identify the way to do it properly.

Regards

Pascal Garcia

Le 21/12/2020 à 17:52, Eddy Verlinden a écrit :

**Comment by eddyverl** [comment]
I've written a workaround. (Not to be proud of, but it might work.)

In the newest version there is a file named "workbenchfolders.py".
In that file you can add your installation folder.  It's pretty obvious.

(You can install/update the workbench with the FreeCAD addon-manager as of now)
Hope this helps.

However the problem with this solution is that when you update your installation your addition might be lost.
Unless it's already in the file on GitHub.

Regards.
